services:
  mongo:
    image: mongo:7
    container_name: henmanager-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: henmanager-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Mongo__ConnectionString=mongodb://mongo:27017
      - Mongo__Database=HenManagerDb
      - Jwt__Key=EstaEsUnaClaveSuperSecretaSuperLarga123456!
      - Jwt__Issuer=HenManager
      - Jwt__Audience=HenManagerClient
    depends_on:
      - mongo
    ports:
      - "5001:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: henmanager-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:5001/api
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  mongo_data:
